query CategoryList(
	$slug: String!
	$currency: String!
	$priceChannel: ID
	$storeId: ID!
	$after: String
	$sortDirection: SortDirection!
	$sortKey: ProductCategorySortKeys!
	$query: String
) {
	category(slug: $slug) {
		id
		name
		slug
		ancestors {
			slug
			name
		}
		products(
			first: 24
			after: $after
			sortDirection: $sortDirection
			sortKey: $sortKey
			priceCurrency: $currency
			priceChannelId: $priceChannel
			storeId: $storeId
			query: $query
		) {
			facets {
				...Facet
			}
			edges {
				node {
					id
					variants {
						totalCount
					}
					...ProductListTile
				}
			}
			totalCount
			pageInfo {
				endCursor
				hasNextPage
			}
		}
	}
}
