query HomePage($storeId: ID!, $currency: String!, $priceChannel: ID) {
	categories(first: 6) {
		edges {
			node {
				id
				name
				slug
				products(storeId: $storeId, priceCurrency: $currency, priceChannelId: $priceChannel) {
					totalCount
				}
			}
		}
	}
	collections(first: 4) {
		edges {
			node {
				id
				name
				slug
				products(first: 0, storeId: $storeId, priceCurrency: $currency, priceChannelId: $priceChannel) {
					totalCount
				}
			}
		}
	}
	products(
		first: 8
		sortKey: ID
		sortDirection: DESC
		storeId: $storeId
		priceCurrency: $currency
		priceChannelId: $priceChannel
	) {
		edges {
			node {
				id
				name
				slug
				heroVariant {
					image {
						src
					}
				}
				priceRange {
					minPrice {
						value {
							centAmount
							currencyCode
							fractionDigits
						}
						discountedPrice {
							value {
								centAmount
								currencyCode
								fractionDigits
							}
						}
					}
				}
			}
		}
	}
}
